spring.application.name=kitchen-operation

server.servlet.context-path=/kitchen-operation

spring.kafka.bootstrap-servers=${KAFKA_BOOTSTRAP_SERVERS:localhost:9092}
spring.kafka.consumer.key-deserializer=org.apache.kafka.common.serialization.StringDeserializer
spring.kafka.consumer.value-deserializer=org.apache.kafka.common.serialization.StringDeserializer
spring.kafka.consumer.auto-offset-reset=earliest
spring.kafka.listener.missing-topics-fatal=false

app.persistence.type=${APP_PERSISTENCE_TYPE:memory}
app.db.url=${APP_DB_URL:jdbc:postgresql://localhost:5432/restaurant}
app.db.username=${APP_DB_USERNAME:restaurant}
app.db.password=${APP_DB_PASSWORD:restaurant}
app.db.schema=${APP_DB_SCHEMA:kitchen_operation}

app.events.kafka-enabled=${APP_EVENTS_KAFKA_ENABLED:false}
app.events.order-menu.group-id=${ORDER_MENU_CONSUMER_GROUP:kitchen-operation-order-menu}
app.events.topic-prefix=kitchen
app.openapi.server-url=${APP_OPENAPI_SERVER_URL:/kitchen-operation}

app.alert.warning-threshold=70
app.alert.critical-threshold=90

springdoc.swagger-ui.path=/swagger-ui.html
springdoc.swagger-ui.operations-sorter=method
springdoc.swagger-ui.tags-sorter=alpha
