spring.application.name=order-menu
server.servlet.context-path=/order-menu

spring.kafka.bootstrap-servers=${KAFKA_BOOTSTRAP_SERVERS:localhost:9092}
spring.kafka.producer.key-serializer=org.apache.kafka.common.serialization.StringSerializer
spring.kafka.producer.value-serializer=org.apache.kafka.common.serialization.StringSerializer
spring.kafka.producer.acks=all
spring.kafka.consumer.key-deserializer=org.apache.kafka.common.serialization.StringDeserializer
spring.kafka.consumer.value-deserializer=org.apache.kafka.common.serialization.StringDeserializer
spring.kafka.consumer.auto-offset-reset=earliest
spring.kafka.listener.missing-topics-fatal=false

app.persistence.type=${APP_PERSISTENCE_TYPE:memory}
app.db.url=${APP_DB_URL:jdbc:postgresql://localhost:5432/restaurant}
app.db.username=${APP_DB_USERNAME:restaurant}
app.db.password=${APP_DB_PASSWORD:restaurant}
app.db.schema=${APP_DB_SCHEMA:order_menu}
app.events.kafka-enabled=${APP_EVENTS_KAFKA_ENABLED:true}
app.events.kitchen.group-id=${KITCHEN_CONSUMER_GROUP:order-menu-kitchen-operation}

springdoc.swagger-ui.path=/swagger-ui.html
springdoc.swagger-ui.operations-sorter=method
springdoc.swagger-ui.tags-sorter=alpha
