spring.application.name=order-menu
spring.kafka.bootstrap-servers=${KAFKA_BOOTSTRAP_SERVERS:localhost:9092}
spring.kafka.producer.key-serializer=org.apache.kafka.common.serialization.StringSerializer
spring.kafka.producer.value-serializer=org.apache.kafka.common.serialization.StringSerializer
spring.kafka.producer.acks=all

app.persistence.type=${APP_PERSISTENCE_TYPE:memory}
app.db.url=${APP_DB_URL:jdbc:postgresql://localhost:5432/restaurant}
app.db.username=${APP_DB_USERNAME:restaurant}
app.db.password=${APP_DB_PASSWORD:restaurant}
app.db.schema=${APP_DB_SCHEMA:order_menu}

springdoc.swagger-ui.path=/swagger-ui.html
springdoc.swagger-ui.operations-sorter=method
springdoc.swagger-ui.tags-sorter=alpha
