export const RESERVATION_SERVICE = Symbol('RESERVATION_SERVICE');
export const AVAILABILITY_SERVICE = Symbol('AVAILABILITY_SERVICE');
export const TABLE_STATE_SERVICE = Symbol('TABLE_STATE_SERVICE');
export const DINING_SESSION_SERVICE = Symbol('DINING_SESSION_SERVICE');

export const RESERVATION_REPOSITORY = Symbol('RESERVATION_REPOSITORY');
export const TABLE_REPOSITORY = Symbol('TABLE_REPOSITORY');
export const DINING_SESSION_REPOSITORY = Symbol('DINING_SESSION_REPOSITORY');

export const EVENT_PUBLISHER = Symbol('EVENT_PUBLISHER');

export const AVAILABILITY_CHECKER = Symbol('AVAILABILITY_CHECKER');
export const WAIT_TIME_ESTIMATOR = Symbol('WAIT_TIME_ESTIMATOR');
export const SERVICE_TIME_TRACKER = Symbol('SERVICE_TIME_TRACKER');
export const RESERVATION_VALIDATOR = Symbol('RESERVATION_VALIDATOR');
export const TABLE_ASSIGNMENT_STRATEGY = Symbol('TABLE_ASSIGNMENT_STRATEGY');

export const RESERVATION_MAPPER = Symbol('RESERVATION_MAPPER');
export const TABLE_MAPPER = Symbol('TABLE_MAPPER');
export const DINING_SESSION_MAPPER = Symbol('DINING_SESSION_MAPPER');
